### ISSUE TITLE
DNASeq Gender classification - issue

### ISSUE THREAD

**Issue by LifeBytesDev** [SexChrLab/SexInference#1] opened 2022-01-19 09:54 UTC
Hi,

I think there is a bug in the below snippet, it should be Y_X_ratio, right? And on what basis the cut-off thresholds are decided?

if X_19_ratio >= 0.5 and Y_19_ratio <= 0.01 and **Y_19_ratio** <= 0.01:
        return "probable_XX"
    else:
        return "probable_XY"

**Comment by tanyaphung** [comment] 2022-01-19 13:23
It's not a bug. Please see the image below. I will try to find some documentation on this when I have more time:
![image](https://user-images.githubusercontent.com/10180091/150139257-0c642680-e453-446f-9781-5e7d6e5b36fc.png)

**Comment by VivekTodur** [comment] 2022-01-19 14:29
Thank you so much for the clarification. Actually **def classify_sex(X_19_ratio, Y_19_ratio, Y_X_ratio):** has 3 arguments passed and only Y_19_ratio was used twice in the code, so i thought it as a bug...

- Vivek Todur

**Comment by tanyaphung** [comment] 2022-01-24 17:26
Hello, 
Yes indeed there was a typo on line 37. I have updated it now. Thanks for catching it. 
I will close this issue now.

**Closed as completed by tanyaphung** 2022-01-24 17:26 UTC
